stages:
  - build

build:
  stage: build
  tags: 
    - build-model
  variables:
        SECURE_FILES_DOWNLOAD_PATH: '.'
  script:
    - curl --silent "https://gitlab.com/yoni980807/download-secure-files/-/raw/yoni980807-main-patch-48835/installer" | bash
    - pip3 install -r requirements.txt --no-cache-dir
    - python3 add-to-db.py build
    - python3 main.py build
    - md5sum subject_reconition_vec.joblib > md5sum4vec.txt
    - md5sum subject_recognition_model.joblib > md5sum4model.txt
  artifacts:
    paths:
      - subject_recognition_model.joblib
      - subject_reconition_vec.joblib
      - md5sum4vec.txt
      - md5sum4model.txt

