stages:
  - build

build:
  stage: build
  tags: 
    - build-model
  image: python:3.11-bullseye
  script:
    - apt-get install git build-essential -y --no-install-recommends
    - pip3 install -r requirements.txt --no-cache-dir
    - python3 add-to-db.py build
    - python3 main.py build
    - md5sum subject_reconition_vec.joblib | awk '{print $1}' > md5sum4vec.txt
    - md5sum subject_recognition_model.joblib  | awk '{print $1}' > md5sum4model.txt
  artifacts:
    paths:
      - subject_recognition_model.joblib
      - subject_reconition_vec.joblib
      - md5sum4vec.txt
      - md5sum4model.txt

